channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bcftools=1.3.1
  - bedtools=2.26.0
  - bwa=0.7.13
  - graphviz=2.38.0
  - python=3.5.1
  - samtools=1.6
  - STAR=2.5.3a
  - snakemake=3.11.0
  - pyyaml=3.11
